# Generated by Django 2.2.1 on 2019-06-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190601_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='select a genre for this book', to='catalog.Genre'),
        ),
    ]
